export const galleryItems = [
  { id: 1, title: "Jianyoon 用户入口", file: "/gallery/gallery-01.png", commentIds: [2] },
  { id: 2, title: "模型额度概览", file: "/gallery/gallery-02.png", commentIds: [5] },
  { id: 3, title: "模型调用明细", file: "/gallery/gallery-03.png", commentIds: [7, 9, 12, 25, 26, 29] },
  { id: 4, title: "0.18 倍率宣传海报", file: "/gallery/gallery-04.png", commentIds: [15, 32] },
  { id: 5, title: "模型接入页面", file: "/gallery/gallery-05.png", commentIds: [34] },
  { id: 6, title: "调用记录横图", file: "/gallery/gallery-06.png", commentIds: [37] },
  { id: 7, title: "模型调用明细（二）", file: "/gallery/gallery-07.png", commentIds: [46] },
  { id: 8, title: "模型调用明细（三）", file: "/gallery/gallery-08.png", commentIds: [48] },
  { id: 9, title: "模型倍率对比", file: "/gallery/gallery-09.png", commentIds: [66] },
  { id: 10, title: "Pro 20x 号池倍率", file: "/gallery/gallery-10.png", commentIds: [67] },
  { id: 11, title: "模型列表截图", file: "/gallery/gallery-11.png", commentIds: [2] },
  { id: 12, title: "模型接入页面（二）", file: "/gallery/gallery-12.png", commentIds: [30] },
  { id: 13, title: "常用模型倍率", file: "/gallery/gallery-13.png", commentIds: [52] },
  { id: 14, title: "编程模型倍率", file: "/gallery/gallery-14.png", commentIds: [53] },
  { id: 15, title: "模型管理后台", file: "/gallery/gallery-15.png", commentIds: [56] },
];
